language: node_js

node_js:
  - 10.15.3

branches:
  only:
    - master


install:
  - npm install
  - npm install --save -g @angular/cli @angular-devkit/build-angular @angular/compiler @angular/compiler-cli --silent

script:
  - ng build 
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

